#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="whomake_database_on")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Inserttasks(tasks instance);
    partial void Updatetasks(tasks instance);
    partial void Deletetasks(tasks instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::DataBase.Properties.Settings.Default.whomake_database_onConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bought_task> bought_task
		{
			get
			{
				return this.GetTable<bought_task>();
			}
		}
		
		public System.Data.Linq.Table<users> users
		{
			get
			{
				return this.GetTable<users>();
			}
		}
		
		public System.Data.Linq.Table<category> category
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		public System.Data.Linq.Table<category_performers> category_performers
		{
			get
			{
				return this.GetTable<category_performers>();
			}
		}
		
		public System.Data.Linq.Table<offer_tasks> offer_tasks
		{
			get
			{
				return this.GetTable<offer_tasks>();
			}
		}
		
		public System.Data.Linq.Table<operations_history> operations_history
		{
			get
			{
				return this.GetTable<operations_history>();
			}
		}
		
		public System.Data.Linq.Table<performers> performers
		{
			get
			{
				return this.GetTable<performers>();
			}
		}
		
		public System.Data.Linq.Table<red_admin_red> red_admin_red
		{
			get
			{
				return this.GetTable<red_admin_red>();
			}
		}
		
		public System.Data.Linq.Table<services> services
		{
			get
			{
				return this.GetTable<services>();
			}
		}
		
		public System.Data.Linq.Table<session> session
		{
			get
			{
				return this.GetTable<session>();
			}
		}
		
		public System.Data.Linq.Table<tasks> tasks
		{
			get
			{
				return this.GetTable<tasks>();
			}
		}
		
		public System.Data.Linq.Table<uploads_images> uploads_images
		{
			get
			{
				return this.GetTable<uploads_images>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bought_task")]
	public partial class bought_task
	{
		
		private int _bought_task_id;
		
		private int _bought_task_id_person;
		
		private int _bought_task_id_task;
		
		public bought_task()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bought_task_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int bought_task_id
		{
			get
			{
				return this._bought_task_id;
			}
			set
			{
				if ((this._bought_task_id != value))
				{
					this._bought_task_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bought_task_id_person", DbType="Int NOT NULL")]
		public int bought_task_id_person
		{
			get
			{
				return this._bought_task_id_person;
			}
			set
			{
				if ((this._bought_task_id_person != value))
				{
					this._bought_task_id_person = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bought_task_id_task", DbType="Int NOT NULL")]
		public int bought_task_id_task
		{
			get
			{
				return this._bought_task_id_task;
			}
			set
			{
				if ((this._bought_task_id_task != value))
				{
					this._bought_task_id_task = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class users
	{
		
		private int _users_id;
		
		private string _users_name;
		
		private string _users_secname;
		
		private string _users_pass;
		
		private string _users_email;
		
		private System.Nullable<double> _users_money;
		
		private System.Nullable<int> _users_accept;
		
		private System.Nullable<System.DateTime> _users_regdate;
		
		private string _users_ip;
		
		private System.Nullable<int> _users_ban;
		
		public users()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int users_id
		{
			get
			{
				return this._users_id;
			}
			set
			{
				if ((this._users_id != value))
				{
					this._users_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_name", DbType="VarChar(50)")]
		public string users_name
		{
			get
			{
				return this._users_name;
			}
			set
			{
				if ((this._users_name != value))
				{
					this._users_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_secname", DbType="VarChar(100)")]
		public string users_secname
		{
			get
			{
				return this._users_secname;
			}
			set
			{
				if ((this._users_secname != value))
				{
					this._users_secname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_pass", DbType="VarChar(500)")]
		public string users_pass
		{
			get
			{
				return this._users_pass;
			}
			set
			{
				if ((this._users_pass != value))
				{
					this._users_pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_email", DbType="VarChar(100)")]
		public string users_email
		{
			get
			{
				return this._users_email;
			}
			set
			{
				if ((this._users_email != value))
				{
					this._users_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_money", DbType="Float")]
		public System.Nullable<double> users_money
		{
			get
			{
				return this._users_money;
			}
			set
			{
				if ((this._users_money != value))
				{
					this._users_money = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_accept", DbType="Int")]
		public System.Nullable<int> users_accept
		{
			get
			{
				return this._users_accept;
			}
			set
			{
				if ((this._users_accept != value))
				{
					this._users_accept = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_regdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> users_regdate
		{
			get
			{
				return this._users_regdate;
			}
			set
			{
				if ((this._users_regdate != value))
				{
					this._users_regdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_ip", DbType="VarChar(50)")]
		public string users_ip
		{
			get
			{
				return this._users_ip;
			}
			set
			{
				if ((this._users_ip != value))
				{
					this._users_ip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_ban", DbType="Int")]
		public System.Nullable<int> users_ban
		{
			get
			{
				return this._users_ban;
			}
			set
			{
				if ((this._users_ban != value))
				{
					this._users_ban = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
	public partial class category
	{
		
		private int _category_id;
		
		private string _category_name;
		
		private int _category_price;
		
		public category()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this._category_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string category_name
		{
			get
			{
				return this._category_name;
			}
			set
			{
				if ((this._category_name != value))
				{
					this._category_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_price", DbType="Int NOT NULL")]
		public int category_price
		{
			get
			{
				return this._category_price;
			}
			set
			{
				if ((this._category_price != value))
				{
					this._category_price = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category_performers")]
	public partial class category_performers
	{
		
		private int _cat_perf_id;
		
		private int _category_performers_id_person;
		
		private int _category_performers_id_category;
		
		public category_performers()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_perf_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int cat_perf_id
		{
			get
			{
				return this._cat_perf_id;
			}
			set
			{
				if ((this._cat_perf_id != value))
				{
					this._cat_perf_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_performers_id_person", DbType="Int NOT NULL")]
		public int category_performers_id_person
		{
			get
			{
				return this._category_performers_id_person;
			}
			set
			{
				if ((this._category_performers_id_person != value))
				{
					this._category_performers_id_person = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_performers_id_category", DbType="Int NOT NULL")]
		public int category_performers_id_category
		{
			get
			{
				return this._category_performers_id_category;
			}
			set
			{
				if ((this._category_performers_id_category != value))
				{
					this._category_performers_id_category = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.offer_tasks")]
	public partial class offer_tasks
	{
		
		private int _offer_tasks_id;
		
		private System.Nullable<int> _offer_tasks_id_person;
		
		private System.Nullable<int> _offer_tasks_id_task;
		
		private System.Nullable<int> _offer_tasks_id_who;
		
		private string _offer_tasks_name;
		
		public offer_tasks()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offer_tasks_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int offer_tasks_id
		{
			get
			{
				return this._offer_tasks_id;
			}
			set
			{
				if ((this._offer_tasks_id != value))
				{
					this._offer_tasks_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offer_tasks_id_person", DbType="Int")]
		public System.Nullable<int> offer_tasks_id_person
		{
			get
			{
				return this._offer_tasks_id_person;
			}
			set
			{
				if ((this._offer_tasks_id_person != value))
				{
					this._offer_tasks_id_person = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offer_tasks_id_task", DbType="Int")]
		public System.Nullable<int> offer_tasks_id_task
		{
			get
			{
				return this._offer_tasks_id_task;
			}
			set
			{
				if ((this._offer_tasks_id_task != value))
				{
					this._offer_tasks_id_task = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offer_tasks_id_who", DbType="Int")]
		public System.Nullable<int> offer_tasks_id_who
		{
			get
			{
				return this._offer_tasks_id_who;
			}
			set
			{
				if ((this._offer_tasks_id_who != value))
				{
					this._offer_tasks_id_who = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offer_tasks_name", DbType="VarChar(350)")]
		public string offer_tasks_name
		{
			get
			{
				return this._offer_tasks_name;
			}
			set
			{
				if ((this._offer_tasks_name != value))
				{
					this._offer_tasks_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.operations_history")]
	public partial class operations_history
	{
		
		private System.Nullable<int> _operations_history_id;
		
		private System.Nullable<int> _operations_history_id_person;
		
		private System.Nullable<int> _operations_history_sum;
		
		private System.Nullable<System.DateTime> _operations_history_date;
		
		private System.Nullable<int> _operations_history_id_task;
		
		private System.Nullable<int> _operations_history_raise;
		
		public operations_history()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operations_history_id", DbType="Int")]
		public System.Nullable<int> operations_history_id
		{
			get
			{
				return this._operations_history_id;
			}
			set
			{
				if ((this._operations_history_id != value))
				{
					this._operations_history_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operations_history_id_person", DbType="Int")]
		public System.Nullable<int> operations_history_id_person
		{
			get
			{
				return this._operations_history_id_person;
			}
			set
			{
				if ((this._operations_history_id_person != value))
				{
					this._operations_history_id_person = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operations_history_sum", DbType="Int")]
		public System.Nullable<int> operations_history_sum
		{
			get
			{
				return this._operations_history_sum;
			}
			set
			{
				if ((this._operations_history_sum != value))
				{
					this._operations_history_sum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operations_history_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> operations_history_date
		{
			get
			{
				return this._operations_history_date;
			}
			set
			{
				if ((this._operations_history_date != value))
				{
					this._operations_history_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operations_history_id_task", DbType="Int")]
		public System.Nullable<int> operations_history_id_task
		{
			get
			{
				return this._operations_history_id_task;
			}
			set
			{
				if ((this._operations_history_id_task != value))
				{
					this._operations_history_id_task = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operations_history_raise", DbType="Int")]
		public System.Nullable<int> operations_history_raise
		{
			get
			{
				return this._operations_history_raise;
			}
			set
			{
				if ((this._operations_history_raise != value))
				{
					this._operations_history_raise = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.performers")]
	public partial class performers
	{
		
		private int _performers_id;
		
		private string _performers_name;
		
		private string _performers_secname;
		
		private System.Nullable<int> _performers_age;
		
		private string _performers_photo;
		
		private string _performers_yourself;
		
		private string _performers_services;
		
		private string _performers_works;
		
		private string _performers_phone;
		
		private string _performers_email;
		
		private System.Nullable<int> _performers_id_person;
		
		private string _performers_status;
		
		private System.Nullable<int> _performers_money;
		
		private System.Nullable<int> _performers_viewes;
		
		private System.Nullable<System.DateTime> _performers_datereg;
		
		private System.Nullable<System.DateTime> _performers_last;
		
		public performers()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int performers_id
		{
			get
			{
				return this._performers_id;
			}
			set
			{
				if ((this._performers_id != value))
				{
					this._performers_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_name", DbType="VarChar(100)")]
		public string performers_name
		{
			get
			{
				return this._performers_name;
			}
			set
			{
				if ((this._performers_name != value))
				{
					this._performers_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_secname", DbType="VarChar(100)")]
		public string performers_secname
		{
			get
			{
				return this._performers_secname;
			}
			set
			{
				if ((this._performers_secname != value))
				{
					this._performers_secname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_age", DbType="Int")]
		public System.Nullable<int> performers_age
		{
			get
			{
				return this._performers_age;
			}
			set
			{
				if ((this._performers_age != value))
				{
					this._performers_age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_photo", DbType="VarChar(500)")]
		public string performers_photo
		{
			get
			{
				return this._performers_photo;
			}
			set
			{
				if ((this._performers_photo != value))
				{
					this._performers_photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_yourself", DbType="VarChar(1000)")]
		public string performers_yourself
		{
			get
			{
				return this._performers_yourself;
			}
			set
			{
				if ((this._performers_yourself != value))
				{
					this._performers_yourself = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_services", DbType="VarChar(1000)")]
		public string performers_services
		{
			get
			{
				return this._performers_services;
			}
			set
			{
				if ((this._performers_services != value))
				{
					this._performers_services = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_works", DbType="VarChar(1000)")]
		public string performers_works
		{
			get
			{
				return this._performers_works;
			}
			set
			{
				if ((this._performers_works != value))
				{
					this._performers_works = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_phone", DbType="VarChar(15)")]
		public string performers_phone
		{
			get
			{
				return this._performers_phone;
			}
			set
			{
				if ((this._performers_phone != value))
				{
					this._performers_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_email", DbType="VarChar(100)")]
		public string performers_email
		{
			get
			{
				return this._performers_email;
			}
			set
			{
				if ((this._performers_email != value))
				{
					this._performers_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_id_person", DbType="Int")]
		public System.Nullable<int> performers_id_person
		{
			get
			{
				return this._performers_id_person;
			}
			set
			{
				if ((this._performers_id_person != value))
				{
					this._performers_id_person = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_status", DbType="VarChar(50)")]
		public string performers_status
		{
			get
			{
				return this._performers_status;
			}
			set
			{
				if ((this._performers_status != value))
				{
					this._performers_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_money", DbType="Int")]
		public System.Nullable<int> performers_money
		{
			get
			{
				return this._performers_money;
			}
			set
			{
				if ((this._performers_money != value))
				{
					this._performers_money = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_viewes", DbType="Int")]
		public System.Nullable<int> performers_viewes
		{
			get
			{
				return this._performers_viewes;
			}
			set
			{
				if ((this._performers_viewes != value))
				{
					this._performers_viewes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_datereg", DbType="Date")]
		public System.Nullable<System.DateTime> performers_datereg
		{
			get
			{
				return this._performers_datereg;
			}
			set
			{
				if ((this._performers_datereg != value))
				{
					this._performers_datereg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performers_last", DbType="DateTime")]
		public System.Nullable<System.DateTime> performers_last
		{
			get
			{
				return this._performers_last;
			}
			set
			{
				if ((this._performers_last != value))
				{
					this._performers_last = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.red_admin_red")]
	public partial class red_admin_red
	{
		
		private int _red_admin_red_id;
		
		private string _red_admin_red_email;
		
		private string _red_admin_red_pass;
		
		public red_admin_red()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_red_admin_red_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int red_admin_red_id
		{
			get
			{
				return this._red_admin_red_id;
			}
			set
			{
				if ((this._red_admin_red_id != value))
				{
					this._red_admin_red_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_red_admin_red_email", DbType="VarChar(100)")]
		public string red_admin_red_email
		{
			get
			{
				return this._red_admin_red_email;
			}
			set
			{
				if ((this._red_admin_red_email != value))
				{
					this._red_admin_red_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_red_admin_red_pass", DbType="VarChar(500)")]
		public string red_admin_red_pass
		{
			get
			{
				return this._red_admin_red_pass;
			}
			set
			{
				if ((this._red_admin_red_pass != value))
				{
					this._red_admin_red_pass = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.services")]
	public partial class services
	{
		
		private int _services_id;
		
		private int _services_id_category;
		
		private string _services_name;
		
		public services()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_services_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int services_id
		{
			get
			{
				return this._services_id;
			}
			set
			{
				if ((this._services_id != value))
				{
					this._services_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_services_id_category", DbType="Int NOT NULL")]
		public int services_id_category
		{
			get
			{
				return this._services_id_category;
			}
			set
			{
				if ((this._services_id_category != value))
				{
					this._services_id_category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_services_name", DbType="VarChar(100)")]
		public string services_name
		{
			get
			{
				return this._services_name;
			}
			set
			{
				if ((this._services_name != value))
				{
					this._services_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.session")]
	public partial class session
	{
		
		private string _id_session;
		
		private System.Nullable<System.DateTime> _putdate;
		
		private string _user;
		
		private string _ip;
		
		public session()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_session", DbType="VarChar(200)")]
		public string id_session
		{
			get
			{
				return this._id_session;
			}
			set
			{
				if ((this._id_session != value))
				{
					this._id_session = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_putdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> putdate
		{
			get
			{
				return this._putdate;
			}
			set
			{
				if ((this._putdate != value))
				{
					this._putdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[user]", Storage="_user", DbType="VarChar(100)")]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this._user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="VarChar(50)")]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this._ip = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tasks")]
	public partial class tasks : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tasks_id;
		
		private int _tasks_id_person;
		
		private int _tasks_category;
		
		private int _tasks_service;
		
		private string _tasks_name;
		
		private string _tasks_description;
		
		private int _tasks_price;
		
		private string _tasks_phone;
		
		private System.Nullable<System.DateTime> _tasks_date_begin;
		
		private System.Nullable<System.DateTime> _tasks_date_end;
		
		private System.Nullable<System.DateTime> _tasks_date_exeq_begin;
		
		private System.Nullable<System.TimeSpan> _tasks_time_exeq_begin;
		
		private System.Nullable<System.DateTime> _tasks_date_exeq_end;
		
		private System.Nullable<System.TimeSpan> _tasks_time_exeq_end;
		
		private string _tasks_adres;
		
		private string _tasks_name_person;
		
		private string _tasks_secname_person;
		
		private System.DateTime _tasks_creation;
		
		private string _tasks_status;
		
		private int _tasks_views;
		
		private int _tasks_money;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontasks_idChanging(int value);
    partial void Ontasks_idChanged();
    partial void Ontasks_id_personChanging(int value);
    partial void Ontasks_id_personChanged();
    partial void Ontasks_categoryChanging(int value);
    partial void Ontasks_categoryChanged();
    partial void Ontasks_serviceChanging(int value);
    partial void Ontasks_serviceChanged();
    partial void Ontasks_nameChanging(string value);
    partial void Ontasks_nameChanged();
    partial void Ontasks_descriptionChanging(string value);
    partial void Ontasks_descriptionChanged();
    partial void Ontasks_priceChanging(int value);
    partial void Ontasks_priceChanged();
    partial void Ontasks_phoneChanging(string value);
    partial void Ontasks_phoneChanged();
    partial void Ontasks_date_beginChanging(System.Nullable<System.DateTime> value);
    partial void Ontasks_date_beginChanged();
    partial void Ontasks_date_endChanging(System.Nullable<System.DateTime> value);
    partial void Ontasks_date_endChanged();
    partial void Ontasks_date_exeq_beginChanging(System.Nullable<System.DateTime> value);
    partial void Ontasks_date_exeq_beginChanged();
    partial void Ontasks_time_exeq_beginChanging(System.Nullable<System.TimeSpan> value);
    partial void Ontasks_time_exeq_beginChanged();
    partial void Ontasks_date_exeq_endChanging(System.Nullable<System.DateTime> value);
    partial void Ontasks_date_exeq_endChanged();
    partial void Ontasks_time_exeq_endChanging(System.Nullable<System.TimeSpan> value);
    partial void Ontasks_time_exeq_endChanged();
    partial void Ontasks_adresChanging(string value);
    partial void Ontasks_adresChanged();
    partial void Ontasks_name_personChanging(string value);
    partial void Ontasks_name_personChanged();
    partial void Ontasks_secname_personChanging(string value);
    partial void Ontasks_secname_personChanged();
    partial void Ontasks_creationChanging(System.DateTime value);
    partial void Ontasks_creationChanged();
    partial void Ontasks_statusChanging(string value);
    partial void Ontasks_statusChanged();
    partial void Ontasks_viewsChanging(int value);
    partial void Ontasks_viewsChanged();
    partial void Ontasks_moneyChanging(int value);
    partial void Ontasks_moneyChanged();
    #endregion
		
		public tasks()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tasks_id
		{
			get
			{
				return this._tasks_id;
			}
			set
			{
				if ((this._tasks_id != value))
				{
					this.Ontasks_idChanging(value);
					this.SendPropertyChanging();
					this._tasks_id = value;
					this.SendPropertyChanged("tasks_id");
					this.Ontasks_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_id_person", DbType="Int NOT NULL")]
		public int tasks_id_person
		{
			get
			{
				return this._tasks_id_person;
			}
			set
			{
				if ((this._tasks_id_person != value))
				{
					this.Ontasks_id_personChanging(value);
					this.SendPropertyChanging();
					this._tasks_id_person = value;
					this.SendPropertyChanged("tasks_id_person");
					this.Ontasks_id_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_category", DbType="Int NOT NULL")]
		public int tasks_category
		{
			get
			{
				return this._tasks_category;
			}
			set
			{
				if ((this._tasks_category != value))
				{
					this.Ontasks_categoryChanging(value);
					this.SendPropertyChanging();
					this._tasks_category = value;
					this.SendPropertyChanged("tasks_category");
					this.Ontasks_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_service", DbType="Int NOT NULL")]
		public int tasks_service
		{
			get
			{
				return this._tasks_service;
			}
			set
			{
				if ((this._tasks_service != value))
				{
					this.Ontasks_serviceChanging(value);
					this.SendPropertyChanging();
					this._tasks_service = value;
					this.SendPropertyChanged("tasks_service");
					this.Ontasks_serviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_name", DbType="VarChar(350) NOT NULL", CanBeNull=false)]
		public string tasks_name
		{
			get
			{
				return this._tasks_name;
			}
			set
			{
				if ((this._tasks_name != value))
				{
					this.Ontasks_nameChanging(value);
					this.SendPropertyChanging();
					this._tasks_name = value;
					this.SendPropertyChanged("tasks_name");
					this.Ontasks_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_description", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string tasks_description
		{
			get
			{
				return this._tasks_description;
			}
			set
			{
				if ((this._tasks_description != value))
				{
					this.Ontasks_descriptionChanging(value);
					this.SendPropertyChanging();
					this._tasks_description = value;
					this.SendPropertyChanged("tasks_description");
					this.Ontasks_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_price", DbType="Int NOT NULL")]
		public int tasks_price
		{
			get
			{
				return this._tasks_price;
			}
			set
			{
				if ((this._tasks_price != value))
				{
					this.Ontasks_priceChanging(value);
					this.SendPropertyChanging();
					this._tasks_price = value;
					this.SendPropertyChanged("tasks_price");
					this.Ontasks_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_phone", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string tasks_phone
		{
			get
			{
				return this._tasks_phone;
			}
			set
			{
				if ((this._tasks_phone != value))
				{
					this.Ontasks_phoneChanging(value);
					this.SendPropertyChanging();
					this._tasks_phone = value;
					this.SendPropertyChanged("tasks_phone");
					this.Ontasks_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_date_begin", DbType="Date")]
		public System.Nullable<System.DateTime> tasks_date_begin
		{
			get
			{
				return this._tasks_date_begin;
			}
			set
			{
				if ((this._tasks_date_begin != value))
				{
					this.Ontasks_date_beginChanging(value);
					this.SendPropertyChanging();
					this._tasks_date_begin = value;
					this.SendPropertyChanged("tasks_date_begin");
					this.Ontasks_date_beginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_date_end", DbType="Date")]
		public System.Nullable<System.DateTime> tasks_date_end
		{
			get
			{
				return this._tasks_date_end;
			}
			set
			{
				if ((this._tasks_date_end != value))
				{
					this.Ontasks_date_endChanging(value);
					this.SendPropertyChanging();
					this._tasks_date_end = value;
					this.SendPropertyChanged("tasks_date_end");
					this.Ontasks_date_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_date_exeq_begin", DbType="Date")]
		public System.Nullable<System.DateTime> tasks_date_exeq_begin
		{
			get
			{
				return this._tasks_date_exeq_begin;
			}
			set
			{
				if ((this._tasks_date_exeq_begin != value))
				{
					this.Ontasks_date_exeq_beginChanging(value);
					this.SendPropertyChanging();
					this._tasks_date_exeq_begin = value;
					this.SendPropertyChanged("tasks_date_exeq_begin");
					this.Ontasks_date_exeq_beginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_time_exeq_begin", DbType="Time")]
		public System.Nullable<System.TimeSpan> tasks_time_exeq_begin
		{
			get
			{
				return this._tasks_time_exeq_begin;
			}
			set
			{
				if ((this._tasks_time_exeq_begin != value))
				{
					this.Ontasks_time_exeq_beginChanging(value);
					this.SendPropertyChanging();
					this._tasks_time_exeq_begin = value;
					this.SendPropertyChanged("tasks_time_exeq_begin");
					this.Ontasks_time_exeq_beginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_date_exeq_end", DbType="Date")]
		public System.Nullable<System.DateTime> tasks_date_exeq_end
		{
			get
			{
				return this._tasks_date_exeq_end;
			}
			set
			{
				if ((this._tasks_date_exeq_end != value))
				{
					this.Ontasks_date_exeq_endChanging(value);
					this.SendPropertyChanging();
					this._tasks_date_exeq_end = value;
					this.SendPropertyChanged("tasks_date_exeq_end");
					this.Ontasks_date_exeq_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_time_exeq_end", DbType="Time")]
		public System.Nullable<System.TimeSpan> tasks_time_exeq_end
		{
			get
			{
				return this._tasks_time_exeq_end;
			}
			set
			{
				if ((this._tasks_time_exeq_end != value))
				{
					this.Ontasks_time_exeq_endChanging(value);
					this.SendPropertyChanging();
					this._tasks_time_exeq_end = value;
					this.SendPropertyChanged("tasks_time_exeq_end");
					this.Ontasks_time_exeq_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_adres", DbType="VarChar(350) NOT NULL", CanBeNull=false)]
		public string tasks_adres
		{
			get
			{
				return this._tasks_adres;
			}
			set
			{
				if ((this._tasks_adres != value))
				{
					this.Ontasks_adresChanging(value);
					this.SendPropertyChanging();
					this._tasks_adres = value;
					this.SendPropertyChanged("tasks_adres");
					this.Ontasks_adresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_name_person", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string tasks_name_person
		{
			get
			{
				return this._tasks_name_person;
			}
			set
			{
				if ((this._tasks_name_person != value))
				{
					this.Ontasks_name_personChanging(value);
					this.SendPropertyChanging();
					this._tasks_name_person = value;
					this.SendPropertyChanged("tasks_name_person");
					this.Ontasks_name_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_secname_person", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string tasks_secname_person
		{
			get
			{
				return this._tasks_secname_person;
			}
			set
			{
				if ((this._tasks_secname_person != value))
				{
					this.Ontasks_secname_personChanging(value);
					this.SendPropertyChanging();
					this._tasks_secname_person = value;
					this.SendPropertyChanged("tasks_secname_person");
					this.Ontasks_secname_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_creation", DbType="DateTime NOT NULL")]
		public System.DateTime tasks_creation
		{
			get
			{
				return this._tasks_creation;
			}
			set
			{
				if ((this._tasks_creation != value))
				{
					this.Ontasks_creationChanging(value);
					this.SendPropertyChanging();
					this._tasks_creation = value;
					this.SendPropertyChanged("tasks_creation");
					this.Ontasks_creationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_status", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string tasks_status
		{
			get
			{
				return this._tasks_status;
			}
			set
			{
				if ((this._tasks_status != value))
				{
					this.Ontasks_statusChanging(value);
					this.SendPropertyChanging();
					this._tasks_status = value;
					this.SendPropertyChanged("tasks_status");
					this.Ontasks_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_views", DbType="Int NOT NULL")]
		public int tasks_views
		{
			get
			{
				return this._tasks_views;
			}
			set
			{
				if ((this._tasks_views != value))
				{
					this.Ontasks_viewsChanging(value);
					this.SendPropertyChanging();
					this._tasks_views = value;
					this.SendPropertyChanged("tasks_views");
					this.Ontasks_viewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasks_money", DbType="Int NOT NULL")]
		public int tasks_money
		{
			get
			{
				return this._tasks_money;
			}
			set
			{
				if ((this._tasks_money != value))
				{
					this.Ontasks_moneyChanging(value);
					this.SendPropertyChanging();
					this._tasks_money = value;
					this.SendPropertyChanged("tasks_money");
					this.Ontasks_moneyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uploads_images")]
	public partial class uploads_images
	{
		
		private int _id;
		
		private int _person_id;
		
		private string _image;
		
		public uploads_images()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_person_id", DbType="Int NOT NULL")]
		public int person_id
		{
			get
			{
				return this._person_id;
			}
			set
			{
				if ((this._person_id != value))
				{
					this._person_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
